### ISSUE TITLE
Extent of commands?

### ISSUE THREAD

**Issue by dark-swordsman** [TechFortress/DisablePvP#1]
Hello,

I was looking into this plugin for my server.

My goal is to only allow users to disable PvP on their own claims, so four questions:

- Can a user disable PvP in *any* claim, or only their claims?
- Can a user disable PvP in claims that they are trusted in? If so, what level of trust for GP do they need to do it?
- When you enable/disable it, does it apply to only that claim, or all the claims that a user owns?
- Is there a way to remove the `/pvp` command for a player to completely disable PvP for themselves?

**Comment by RoboMWM** [comment]
- Player needs /permissiontrust or to be owner to run /pvp
- Only applies to the claim, don't believe I made it possible to perform on any claim
- Other than hiding it away with the bukkit-provided `commands.yml`, no. But, I could honor a request for a version that has this removed. (I've actually modified this plugin to remove the claim portions in an effort to simplify this plugin's purpose and the (relatively) recent changes to my server.)

**Comment by RoboMWM** [comment]
Actually, the version I made for cities7 might be the one you're looking for. If so, then you're in luck for a free-of-charge variation that you desire: https://ci.appveyor.com/project/RoboMWM39862/disablepvp/builds/34045658/artifacts

**Comment by dark-swordsman** [comment]
Sick! That's exactly what I needed. It seems to work perfectly on 1.16.1 with GP 16.14.0. Thanks!

Is there any hope that version will stay updated for future GP and MC versions? I would assume based on the simple functionality that it shouldn't need to really be updated, right?

**Comment by RoboMWM** [comment]
No guarantees.

Depending on the scope I may or may not provide free updates as needed.

**Comment by dark-swordsman** [comment]
So it seems that the one you linked doesn't work properly with GP 16.14.0. I think I might just use the original DisablePvP plugin, though, I don't see a jar for it. 

Do I need to compile it myself? If so, what do I need to do to compile it? I have gradle installed, but I'm not sure how to go about that.

**Comment by dark-swordsman** [comment]
I actually found a master build on your site [here](https://ci.appveyor.com/project/RoboMWM39862/disablepvp/builds/34045640/artifacts).

Though, it appears `/claimpvp` is not even a command in this version.

**Comment by RoboMWM** [comment]
it doesn't work properly? As in...?

But yes as mentioned prior I removed that command.
